-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."softcartDimDate"
(
    dateid smallint NOT NULL,
    date date,
    year smallint,
    quarter smallint,
    "quarterName" character varying(10),
    month smallint,
    "monthName" character varying(10),
    day smallint,
    "weekDay" smallint,
    "weekDayName" character varying(10),
    PRIMARY KEY (dateid)
);

CREATE TABLE public."softcartDimCategory"
(
    categoryid smallint NOT NULL,
    chategory character varying(32),
    PRIMARY KEY (categoryid)
);

CREATE TABLE public."softcartDimItem"
(
    itemid smallint NOT NULL,
    item character varying(32),
    PRIMARY KEY (itemid)
);

CREATE TABLE public."softcartDimCountry"
(
    countryid smallint NOT NULL,
    country character varying(32),
    PRIMARY KEY (countryid)
);

CREATE TABLE public."softcartFactSales"
(
    orderid bigint NOT NULL,
    dateid smallint,
    countryid smallint,
    categoryid smallint,
    itemid smallint,
    amount bigint,
    PRIMARY KEY (orderid)
);

ALTER TABLE public."softcartFactSales"
    ADD FOREIGN KEY (dateid)
    REFERENCES public."softcartDimDate" (dateid)
    NOT VALID;


ALTER TABLE public."softcartFactSales"
    ADD FOREIGN KEY (countryid)
    REFERENCES public."softcartDimCountry" (countryid)
    NOT VALID;


ALTER TABLE public."softcartFactSales"
    ADD FOREIGN KEY (categoryid)
    REFERENCES public."softcartDimCategory" (categoryid)
    NOT VALID;


ALTER TABLE public."softcartFactSales"
    ADD FOREIGN KEY (itemid)
    REFERENCES public."softcartDimItem" (itemid)
    NOT VALID;

END;